const plants = [
  {
    id: 1,
    name: "Thuja Smaragd (Emerald Green)",
    latin: "Thuja occidentalis 'Smaragd'",
    category: "thuja",
    tags: ["thuja", "hedge"],
    price: 25,
    unit: "per plant",
    height: "80–100 cm",
    age: "3 years",
    stock: "available",
    description: "Classic pyramid-shaped Thuja with bright emerald foliage. Perfect for hedges and privacy screens. Grows well in Georgian climate, drought-tolerant once established. Ready for planting now — will fill out nicely in 3–6 months.",
    seller: "Giorgi's Nursery",
    sellerId: 1000,
    phone: "+995 555 123 456",
    location: "Tbilisi, Dighomi",
    image: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&h=400&fit=crop"
  },
  {
    id: 2,
    name: "Thuja Brabant (Fast Grower)",
    latin: "Thuja occidentalis 'Brabant'",
    category: "thuja",
    tags: ["thuja", "hedge"],
    price: 20,
    unit: "per plant",
    height: "100–120 cm",
    age: "3–4 years",
    stock: "available",
    description: "The fastest growing Thuja variety — ideal if you need a green fence quickly. Adds 30–40 cm per year. Dense foliage provides excellent privacy. Well-rooted and ready for transplanting.",
    seller: "Giorgi's Nursery",
    sellerId: 1000,
    phone: "+995 555 123 456",
    location: "Tbilisi, Dighomi",
    image: "https://images.unsplash.com/photo-1598512752271-33f913a5af13?w=600&h=400&fit=crop"
  },
  {
    id: 3,
    name: "Thuja Giant Green",
    latin: "Thuja plicata 'Green Giant'",
    category: "thuja",
    tags: ["thuja", "hedge"],
    price: 35,
    unit: "per plant",
    height: "120–150 cm",
    age: "4 years",
    stock: "limited",
    description: "Premium large Thuja for instant impact. Dark green, dense foliage that stays vibrant year-round. Excellent wind resistance. Limited stock — these go fast in spring season.",
    seller: "Kakheti Green Farm",
    sellerId: 2000,
    phone: "+995 577 234 567",
    location: "Telavi, Kakheti",
    image: "https://images.unsplash.com/photo-1604762524889-3e2fcc145683?w=600&h=400&fit=crop"
  },
  {
    id: 4,
    name: "Thuja Smaragd — Bulk Pack (10 pcs)",
    latin: "Thuja occidentalis 'Smaragd'",
    category: "thuja",
    tags: ["thuja", "hedge"],
    price: 200,
    unit: "pack of 10",
    height: "60–80 cm",
    age: "2 years",
    stock: "available",
    description: "Budget-friendly bulk pack for creating a full hedge line. 10 healthy Smaragd saplings, perfect spacing for a 5-meter fence. Younger plants that will establish roots quickly and grow vigorously in 3–6 months.",
    seller: "Giorgi's Nursery",
    sellerId: 1000,
    phone: "+995 555 123 456",
    location: "Tbilisi, Dighomi",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop"
  },
  {
    id: 5,
    name: "Thuja Golden Globe",
    latin: "Thuja occidentalis 'Golden Globe'",
    category: "thuja",
    tags: ["thuja", "ornamental"],
    price: 30,
    unit: "per plant",
    height: "40–50 cm",
    age: "3 years",
    stock: "available",
    description: "Compact, ball-shaped Thuja with stunning golden-yellow foliage. Perfect for garden borders, rock gardens, or decorative pots. Low maintenance and naturally keeps its round shape.",
    seller: "Batumi Botanics",
    sellerId: 3000,
    phone: "+995 599 345 678",
    location: "Batumi, Adjara",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600&h=400&fit=crop"
  },
  {
    id: 6,
    name: "Thuja Danica (Dwarf)",
    latin: "Thuja occidentalis 'Danica'",
    category: "thuja",
    tags: ["thuja", "ornamental"],
    price: 18,
    unit: "per plant",
    height: "30–40 cm",
    age: "2 years",
    stock: "available",
    description: "Adorable dwarf globe Thuja, perfect for small gardens, balconies, and container planting. Stays compact and round. Very hardy — handles Georgian winters with ease.",
    seller: "Batumi Botanics",
    sellerId: 3000,
    phone: "+995 599 345 678",
    location: "Batumi, Adjara",
    image: "https://images.unsplash.com/photo-1491147334573-44cbb4602074?w=600&h=400&fit=crop"
  },
  {
    id: 7,
    name: "Cherry Laurel Hedge",
    latin: "Prunus laurocerasus",
    category: "hedge",
    tags: ["hedge"],
    price: 15,
    unit: "per plant",
    height: "60–80 cm",
    age: "2 years",
    stock: "available",
    description: "Glossy evergreen hedge plant, very popular in Georgian gardens. Fast growing with beautiful white spring flowers. Creates a dense, lush privacy screen. Tolerates shade well.",
    seller: "Kakheti Green Farm",
    sellerId: 2000,
    phone: "+995 577 234 567",
    location: "Telavi, Kakheti",
    image: "https://images.unsplash.com/photo-1462275646964-a0e3c11f18a6?w=600&h=400&fit=crop"
  },
  {
    id: 8,
    name: "Japanese Maple (Red)",
    latin: "Acer palmatum 'Atropurpureum'",
    category: "ornamental",
    tags: ["ornamental"],
    price: 65,
    unit: "per plant",
    height: "80–100 cm",
    age: "4 years",
    stock: "limited",
    description: "Stunning ornamental tree with deep red-purple leaves. A showpiece for any garden. Prefers partial shade and well-drained soil. Limited availability — grown from selected stock.",
    seller: "Batumi Botanics",
    sellerId: 3000,
    phone: "+995 599 345 678",
    location: "Batumi, Adjara",
    image: "https://images.unsplash.com/photo-1603912699214-92627f304eb6?w=600&h=400&fit=crop"
  },
  {
    id: 9,
    name: "Pomegranate Tree",
    latin: "Punica granatum",
    category: "fruit",
    tags: ["fruit"],
    price: 40,
    unit: "per tree",
    height: "100–130 cm",
    age: "3 years",
    stock: "preorder",
    description: "Traditional Georgian pomegranate, fruit-bearing variety. Will produce fruit within 1–2 seasons. Loves the Georgian sun and well-drained soil. Pre-order for autumn planting season.",
    seller: "Kakheti Green Farm",
    sellerId: 2000,
    phone: "+995 577 234 567",
    location: "Telavi, Kakheti",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&h=400&fit=crop"
  },
  {
    id: 10,
    name: "Fig Tree (Brown Turkey)",
    latin: "Ficus carica 'Brown Turkey'",
    category: "fruit",
    tags: ["fruit"],
    price: 35,
    unit: "per tree",
    height: "90–110 cm",
    age: "3 years",
    stock: "available",
    description: "Reliable fig variety that thrives in Georgian climate. Sweet, juicy fruits ready by late summer. Self-pollinating — only one tree needed. Beautiful large leaves add tropical feel to any garden.",
    seller: "Giorgi's Nursery",
    sellerId: 1000,
    phone: "+995 555 123 456",
    location: "Tbilisi, Dighomi",
    image: "https://images.unsplash.com/photo-1601379760883-1bb497c558e0?w=600&h=400&fit=crop"
  }
];
